import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import Preloader from '@/components/Preloader';

export const metadata: Metadata = {
  title: 'The Arcane Codex',
  description: 'An interactive portfolio codex, generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,400;0,700;1,400&family=Cinzel:wght@400..900&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <Preloader />
        <div id="main-content" className="opacity-0">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
